# -*- coding: utf-8 -*-
"""EDA_Amazon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c474FIRjoNshoaBzPWq8TPYs0boycNJk

**Step 1: Data Collection**
"""

import pandas as pd

df = pd.read_csv('amazon.csv')

df.head()

df.shape

df.info()

df.describe()

"""**Step 2 : DATA CLEANING**"""

df.isnull().sum()

"""**To Check Duplicate Rows**"""

df.duplicated().sum()

"""**To Convert Price Columns to Numeric**"""

df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹','', regex=False)
    .str.replace(',','', regex=False)
    .astype(float)
)

df['actual_price'] = (
    df['actual_price']
    .str.replace('₹','', regex=False)
    .str.replace(',','', regex=False)
    .astype(float)
)

"""**To Convert Discount Percentage**"""

df['discount_percentage'] = (
    df['discount_percentage']
    .str.replace('%','', regex=False)
    .astype(float)
)

"""**To Convert Rating Count**"""

df['rating_count'] = (
    df['rating_count']
    .str.replace(',','', regex=False)
)

df['rating_count'] = pd.to_numeric(
    df['rating_count'],
    errors='coerce'
)

"""**To Verify Conversion**"""

df[['discounted_price',
    'actual_price',
    'discount_percentage',
    'rating',
    'rating_count']].dtypes

"""**Step 3: Statistical Analysis**

**To Generate Statistical Summary**
"""

df[['discounted_price',
    'actual_price',
    'discount_percentage',
    'rating',
    'rating_count']].describe()

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

df['rating'].mean()

df['discount_percentage'].mean()

df['category'].value_counts().head(10)

"""**Step 4: Visualization**

**Graph 1: Distribution of Product Ratings**
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.histplot(df['rating'], bins=15)

plt.title("Distribution of Product Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Products")

plt.show()

"""**Graph 2: Discount Distribution**"""

plt.figure(figsize=(8,5))

sns.histplot(
    df['discount_percentage'],
    bins=20
)

plt.title("Discount Percentage Distribution")
plt.xlabel("Discount (%)")
plt.ylabel("Frequency")

plt.show()

"""**Graph 3: Top 10 Categories**"""

top_categories = df['category'].value_counts().head(10)

plt.figure(figsize=(12,6))

top_categories.plot(kind='bar')

plt.title("Top 10 Product Categories")
plt.xlabel("Category")
plt.ylabel("Count")

plt.xticks(rotation=90)

plt.show()

"""**Graph 4: Correlation Heatmap**"""

corr = df[['discounted_price',
           'actual_price',
           'discount_percentage',
           'rating',
           'rating_count']].corr()

plt.figure(figsize=(8,6))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()

"""**Step 5: Advanced Visualizations**"""

top_reviewed = df.nlargest(
    10,
    'rating_count'
)

plt.figure(figsize=(10,6))

sns.barplot(
    x='rating_count',
    y='product_name',
    data=top_reviewed
)

plt.title("Top 10 Most Reviewed Products")

plt.show()

"""**Price Distribution**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    x=df['actual_price']
)

plt.title("Actual Price Distribution")

plt.show()

"""**Discount vs Rating Scatter Plot**"""

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='discount_percentage',
    y='rating',
    data=df
)

plt.title("Discount Percentage vs Rating")

plt.show()